spring:
  application:
    name: WELCOME-API
  boot:
    admin:
      client:
        url: http://localhost:8390/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9095        
